import{a as w,S as P,i as q}from"./assets/vendor-06b1bbdf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();async function h(o,t){const c="https://pixabay.com",i="/api/",e="?key=43320084-437e2eae51f81b3c91e609ed7",r=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`,s=c+i+e+r;return(await w.get(s)).data}const u=document.querySelector(".gallery");function p(o){const t=o.hits.map(({webformatURL:i,largeImageURL:e,tags:r,likes:s,views:f,comments:S,downloads:v})=>`<li class="gallery-item">
                <a class="gallery-link" href="${e}">
                <img class="gallery-img" src="${i}" alt="${r}">
                <div class="image-description">
                <p>Likes: ${s}</p>
                <p>Views: ${f}</p>
                <p>Comments ${S}</p>
                <p>Downloads ${v}</p>
                </div>
                </a>
                </li>`).join("");u.insertAdjacentHTML("beforeend",t),new P(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const $=document.querySelector(".img-search-form"),g=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");let l,a,y;$.addEventListener("submit",M);m.addEventListener("click",O);async function M(o){if(o.preventDefault(),L(),u.innerHTML="",l=o.target.elements.query.value.trim(),a=1,l===""){n("Sorry, there are no search terms entered. Please try again!");return}b();try{const t=await h(l,a);if(y=Math.ceil(t.totalHits/15),t.totalHits===0){d(),n("Sorry, there are no images matching your search query. Please try again!");return}p(t)}catch(t){n(t)}d(),E(),o.target.reset()}async function O(){a+=1,b();try{const t=await h(l,a);p(t)}catch(t){n(t)}d(),E();const o=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:o*2})}function x(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function n(o){q.error({message:o,messageColor:"white",backgroundColor:"red",position:"topRight"})}function E(){a>=y?(L(),n("We're sorry, but you've reached the end of search results.")):x()}
//# sourceMappingURL=commonHelpers.js.map
